### PR TITLE
fix: validate license early in the metadata process

### LINKED ISSUE #397: bug: license file must be SPDX
When a `pyproject.toml` contains:

```toml
license = { file = "LICENSE.md" }
```

the python backend expects the filename to be a valid SPDX name. E.g. 

```
Error:   × failed to solve requirements of environment 'default' for platform 'win-64'
  ├─▶   × failed to extract metadata for package 'parcels'
  │
  ╰─▶   × Failed to parse recipe

      Error:
        × failed to parse SPDX license: 'LICENSE.md', because: unknown term
        │ See <https://spdx.org/licenses> for the list of valid licenses.
        │ Use 'LicenseRef-<MyLicense>' if you are using a custom license.
        [Failed to read contents for label `here` (offset: 540, length: 10): OutOfBounds]
```

**Reproducible example:**

https://github.com/baszalmstra/pixi-build-python-broken-license

### PR DESCRIPTION
**Pull request by ruben-arts**
Fixes #397 and #488

This will now validate the spdx and otherwise ignore it for now.

It also addes all the files in `license-files`.

⚠️  Also updated the `py-pixi-build-backend` version as the `license-file` changed to `license-files`

### CODE REVIEW

File: crates/pixi-build-python/src/metadata.rs [hunk 1]
```diff
@@ -37,9 +38,24 @@ impl PyprojectMetadataProvider {
...
             ignore_pyproject_manifest,
+            warnings: RefCell::new(Vec::new()),
         }
     }
 
+    /// Returns all warnings collected during metadata extraction.
+    ///
+    /// This includes warnings about invalid SPDX license expressions and other
+    /// metadata parsing issues that don't cause errors but may indicate problems.
+    #[allow(dead_code)]
```
Comment (Hofer-Julian) [inline crates/pixi-build-python/src/metadata.rs]:
```suggestion
    #[expect(unused)]
```
This is nicer, since it fails when you start using it. So you can't forget to remove this attribute

**Comment by ruben-arts** [comment]
> Looks good! Should you also bump other backend versions?

It's only an api change for backend building code right. Not the actual backends.
